### ISSUE TITLE
No output when running run_ALL.m

### ISSUE THREAD

**Issue by LingyvKong** [liyangfan0/DOCPF#2]
Hi, thanks for your work. 
But when I run run_ALL.m, there is no output or error. May I ask what effect it should have? Where will the tracking results be saved?

**Comment by liyangfan0** [comment]
Hi, you can set the params.visualization=1 in params.txt, and you will get the visualization results.  If it doesn't work, I will fix the code tomorrow.

**Comment by LingyvKong** [comment]
Hi, thanks for your quick reply. When I set the params.visualization=1, there is still no output or error.  And when I set params.visualization_dbg=1, the error it outputs is as follows:
![image](https://github.com/liyangfan0/DOCPF/assets/35091237/7ab5004c-a45e-4c53-a7d2-a38075f46c22)

**Comment by liyangfan0** [comment]
Hi, I update the trackerMain.m. You can replace the file and try again, I think it will be right now

**Comment by LingyvKong** [comment]
Hi, It works now. Thank you~
